name: eShopOnWeb Build, Test, and Deploy

# Trigger
on: [push, workflow_dispatch]

# Environment variables
env:
  RESOURCE-GROUP: rg-az400-eshoponweb-DOESA
  LOCATION: eastus
  TEMPLATE-FILE: .azure/bicep/webapp.bicep
  SUBSCRIPTION-ID: b4606ffd-a21a-4c82-9a9e-1982b3bd56a5
  WEBAPP-NAME: az400-webapp-DOESA
  DOTNET_ROOT: C:\Users\runneradmin\AppData\Local\Microsoft\dotnet

jobs:
  # Build .net web project in repository
  build:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
notification demo
      # Prepare runner for desired .net version SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      # Build the .net project
      - name: Build with dotnet
        run: dotnet build ./src/Web/Web.csproj --configuration Release

      # Publish the .net project
      - name: dotnet publish
        run: dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      # Upload the published website code artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      # Upload the Bicep template artifacts
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: bicep-template
          path: .azure/bicep

  # Test .net web project in repository
  test:
    runs-on: windows-latest
    needs: build
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Prepare runner for desired .net version SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      # Test the .net project
      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

  # Use Bicep to deploy infrastructure + Publish webapp
  deploy:
    runs-on: windows-latest
    needs: [build, test]
    environment:
      name: 'Development'
    steps:
      # Download the publish files created in the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
          path: .net-app

      # Download the Bicep templates from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: bicep-template
          path: bicep-template

      # Login to Azure subscription using a service principal (credentials stored as GitHub Secret in repo)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Azure WebApp using Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/webapp.bicep
          parameters: 'webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}'
          failOnStdErr: false

      # Publish website to Azure App Service (WebApp)
      - name: Publish Website to WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP-NAME }}
          package: .net-app

  notify:
    runs-on: windows-latest
    needs: [build, test, deploy]
    if: failure()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send GitHub Actions Notification
        run: |
          echo "Build or deployment failed! Check the GitHub Actions workflow for details."
