name: eShopOnWeb Build, Test, and Deploy

# Triggers (uncomment line below to use it)
on: [push, workflow_dispatch]

# Environment variables https://docs.github.com/en/actions/learn-github-actions/environment-variables
env:
  RESOURCE-GROUP: rg-az400-eshoponweb-DOESA
  LOCATION: eastus
  TEMPLATE-FILE: .azure/bicep/webapp.bicep
  SUBSCRIPTION-ID: b4606ffd-a21a-4c82-9a9e-1982b3bd56a5
  WEBAPP-NAME: az400-webapp-DOESA

jobs:
  # Build the .net web project
  build:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      # Prepare runner for desired .net version SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      # Build the .net project
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release
      # Upload the published website code artifacts
      - name: Upload artifact for test job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  # Test the .net web project
  test:
    runs-on: windows-latest
    needs: build
    steps:
      # Download the published files created in the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
          path: .net-app
      # Run tests on the .net project
      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

  # Deploy the .net web project
  deploy:
    runs-on: windows-latest
    needs: test
    environment:
      name: 'Development'
    steps:
      # Download the published files and bicep templates created in the build job
      - name: Download artifacts from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
          path: .net-app
      # (Optional) Download the bicep templates from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: bicep-template
          path: bicep-template
      # (Your existing steps for Azure Login, Bicep Deployment, and WebApp Publishing go here)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/webapp.bicep
          parameters: 'webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}'
          failOnStdErr: false
      - name: Publish Website to WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP-NAME }}
          package: .net-app
